/**
 * Inline HTML templates for the six tender documents (RFQ, quotation,
 * comparative, work order, SO proceedings, Form 19). Tamil + English content
 * is rendered with the bundled Noto Sans Tamil webfont fallback.
 *
 * Templates are pure functions of a context object so they can be unit-tested
 * without any browser dependency.
 */

import { rupeesInWordsEn, rupeesInWordsTa } from './amount-in-words'

export interface TemplateContext {
    panchayat: { id: number; name: string }
    tender: {
        id: number
        title_ta: string | null
        title_en: string | null
        narrative_ta: string | null
        narrative_en: string | null
        anchor_date: Date | null
        work_order_date: Date | null
        work_completed_at: Date | null
        public_token: string | null
        status: string
    }
    timeline: Record<string, string | null>
    line_items: Array<{
        id: number
        seq: number
        description_ta: string | null
        description_en: string | null
        quantity: string | null
        unit: string | null
    }>
    invited_vendors: Array<{ id: number; name: string; phone_e164: string; place: string | null }>
    quotations: Array<{
        id: number
        vendor_id: number | null
        submitter_name: string
        submitter_phone_e164: string
        amount: string
        remarks: string | null
        screening_outcome: string
        superseded_by_id: number | null
    }>
    awarded_quotation_id: number | null
    payment_meta: Record<string, any> | null
    document: { template_id: string; version: number; vendor_id: number | null; field_overrides: Record<string, unknown> | null }
    generated_at: Date
}

const fmtDate = (d: Date | null | undefined) => (d ? new Date(d).toISOString().slice(0, 10) : '—')
const fmtAmount = (s: string | null | undefined) => (s == null ? '—' : Number(s).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 }))
const escape = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[c] as string))

const SHELL = (title: string, body: string) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escape(title)}</title>
<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Tamil:wght@400;600;700&family=Noto+Sans:wght@400;600;700&display=swap" rel="stylesheet" />
<style>
  body { font-family: 'Noto Sans', 'Noto Sans Tamil', system-ui, sans-serif; color: #1a1a1a; line-height: 1.5; padding: 0; margin: 0; }
  .page { padding: 24px 28px; max-width: 720px; margin: 0 auto; }
  .ta { font-family: 'Noto Sans Tamil', 'Noto Sans', sans-serif; }
  h1, h2, h3 { margin: 0 0 8px 0; font-weight: 700; }
  h1 { font-size: 18pt; text-align: center; }
  h2 { font-size: 14pt; }
  h3 { font-size: 12pt; }
  .center { text-align: center; }
  .right { text-align: right; }
  .muted { color: #555; font-size: 9pt; }
  .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 16px; margin-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 16px; font-size: 10pt; }
  th, td { border: 1px solid #444; padding: 6px 8px; vertical-align: top; }
  th { background: #f0f0f0; text-align: left; }
  td.amount { text-align: right; font-variant-numeric: tabular-nums; }
  .l1 { background: #fff7d6; font-weight: 700; }
  .footer { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-top: 32px; }
  .sig { padding-top: 60px; border-top: 1px solid #444; text-align: center; }
  .small { font-size: 9pt; }
  ol.conditions li { margin-bottom: 6px; }
  .stamp-rejected { color: #b00; border: 2px solid #b00; padding: 4px 8px; display: inline-block; transform: rotate(-4deg); }
  .stamp-approved { color: #060; border: 2px solid #060; padding: 4px 8px; display: inline-block; transform: rotate(-2deg); }
  .header-block { border-bottom: 2px solid #222; padding-bottom: 8px; margin-bottom: 12px; }
  .panchayat-name { font-size: 12pt; font-weight: 700; }
  .doc-meta { font-size: 9pt; color: #555; margin-top: 4px; }
</style>
</head>
<body>
<div class="page">
${body}
<div class="muted small" style="margin-top:24px">Generated by Panchayat tender system • ${escape(title)} • Tender #${'{tenderId}'} • v${'{ver}'}</div>
</div>
</body>
</html>`

function header(ctx: TemplateContext, titleTa: string, titleEn: string): string {
    return `<div class="header-block center">
  <div class="panchayat-name ta">${escape(ctx.panchayat.name)} ஊராட்சி</div>
  <div class="panchayat-name">${escape(ctx.panchayat.name)} Panchayat</div>
  <h1 class="ta">${escape(titleTa)}</h1>
  <h2>${escape(titleEn)}</h2>
  <div class="doc-meta">Tender #${ctx.tender.id} • Status: ${escape(ctx.tender.status)} • Generated: ${fmtDate(ctx.generated_at)}</div>
</div>`
}

function lineItemsTable(ctx: TemplateContext): string {
    const rows = ctx.line_items.length
        ? ctx.line_items.map((li) => `
        <tr>
          <td>${li.seq}</td>
          <td class="ta">${escape(li.description_ta || li.description_en || '—')}</td>
          <td>${escape(li.description_en || '—')}</td>
          <td>${escape(li.quantity ?? '—')}</td>
          <td>${escape(li.unit ?? '—')}</td>
        </tr>`).join('')
        : '<tr><td colspan="5" class="muted center">No line items</td></tr>'
    return `<table>
  <thead><tr><th>#</th><th class="ta">விவரம்</th><th>Description</th><th>Qty</th><th>Unit</th></tr></thead>
  <tbody>${rows}</tbody>
</table>`
}

// ── 1. RFQ ────────────────────────────────────────────────────────────────
export function renderRfq(ctx: TemplateContext): string {
    const recipients = ctx.invited_vendors.length
        ? ctx.invited_vendors.map((v) => `<li>${escape(v.name)}${v.place ? `, ${escape(v.place)}` : ''} (${escape(v.phone_e164)})</li>`).join('')
        : '<li class="muted">(No invited vendors)</li>'
    const deadline = ctx.timeline.quotation_deadline ?? '—'
    const body = `
${header(ctx, 'விலைப்புள்ளி கோருதல்', 'Request for Quotation (RFQ)')}
<p class="ta"><strong>பெறுநர்:</strong></p>
<ul>${recipients}</ul>
<p><strong>Subject / பொருள்:</strong> <span class="ta">${escape(ctx.tender.title_ta ?? '')}</span> ${ctx.tender.title_en ? ` / ${escape(ctx.tender.title_en)}` : ''}</p>
<p class="ta">${escape(ctx.tender.narrative_ta ?? '')}</p>
<p>${escape(ctx.tender.narrative_en ?? '')}</p>
${lineItemsTable(ctx)}
<p class="ta"><strong>பதிலளிக்க வேண்டிய கடைசி நாள்:</strong> ${deadline}</p>
<p><strong>Reply deadline:</strong> ${deadline}</p>
<p class="small muted">Public submission link (if open):
  ${ctx.tender.public_token ? `<code>/public/tenders/${ctx.tender.public_token}</code>` : '<em>not yet published</em>'}
</p>
<div class="footer">
  <div></div>
  <div>
    <div class="ta">தனி அலுவலர் / Special Officer</div>
    <div class="sig">Signature</div>
  </div>
</div>`
    return SHELL('RFQ', body).replace('{tenderId}', String(ctx.tender.id)).replace('{ver}', String(ctx.document.version))
}

// ── 2. Quotation letter (per bidder) ──────────────────────────────────────
export function renderQuotation(ctx: TemplateContext): string {
    const targetVendorId = ctx.document.vendor_id
    const q = ctx.quotations.find((x) => x.vendor_id === targetVendorId) || ctx.quotations[0]
    const vendor = ctx.invited_vendors.find((v) => v.id === targetVendorId)
        || (q ? { id: q.vendor_id ?? 0, name: q.submitter_name, phone_e164: q.submitter_phone_e164, place: null } : null)

    if (!q || !vendor) {
        const msg = '<p class="muted">No quotation found for the selected vendor.</p>'
        return SHELL('Quotation', `${header(ctx, 'கொட்டேஷன்', 'Quotation')}${msg}`)
            .replace('{tenderId}', String(ctx.tender.id))
            .replace('{ver}', String(ctx.document.version))
    }

    const stamp = q.screening_outcome === 'rejected'
        ? '<span class="stamp-rejected ta">நிராகரிக்கப்பட்டது / Rejected</span>'
        : q.screening_outcome === 'approved'
            ? '<span class="stamp-approved ta">அங்கீகரிக்கப்பட்டது / Approved</span>'
            : ''
    const body = `
${header(ctx, 'கொட்டேஷன்', 'Quotation')}
<div class="grid">
  <div><strong class="ta">அனுப்புனர் / From:</strong><br/>${escape(vendor.name)}${vendor.place ? `, ${escape(vendor.place)}` : ''}<br/>${escape(vendor.phone_e164)}</div>
  <div><strong class="ta">பெறுநர் / To:</strong><br/>${escape(ctx.panchayat.name)} Panchayat</div>
</div>
<p><strong>Reference:</strong> Tender #${ctx.tender.id} <span class="ta"> (${escape(ctx.tender.title_ta ?? '')})</span></p>
${lineItemsTable(ctx)}
<table>
  <tr><th>Total amount</th><td class="amount">₹ ${fmtAmount(q.amount)}</td></tr>
  <tr><th>In words</th><td class="ta">${escape(rupeesInWordsTa(Number(q.amount)))} <br/><span lang="en">${escape(rupeesInWordsEn(Number(q.amount)))}</span></td></tr>
  ${q.remarks ? `<tr><th>Remarks</th><td>${escape(q.remarks)}</td></tr>` : ''}
</table>
<p>${stamp}</p>
<div class="footer">
  <div></div>
  <div><div>Vendor signature</div><div class="sig">${escape(vendor.name)}</div></div>
</div>`
    return SHELL('Quotation', body).replace('{tenderId}', String(ctx.tender.id)).replace('{ver}', String(ctx.document.version))
}

// ── 3. Comparative statement ──────────────────────────────────────────────
export function renderComparative(ctx: TemplateContext): string {
    const active = ctx.quotations.filter((q) => q.superseded_by_id == null)
    const sorted = [...active].sort((a, b) => Number(a.amount) - Number(b.amount))
    const l1Id = sorted[0]?.id ?? null

    const cols = active.length
        ? active.map((q, i) => `<th>${i + 1}. ${escape(q.submitter_name)}</th>`).join('')
        : '<th class="muted">No quotations</th>'

    const amounts = active.length
        ? active.map((q) => `<td class="amount${q.id === l1Id ? ' l1' : ''}">₹ ${fmtAmount(q.amount)}</td>`).join('')
        : '<td class="muted">—</td>'

    const phones = active.length
        ? active.map((q) => `<td class="small">${escape(q.submitter_phone_e164)}</td>`).join('')
        : '<td>—</td>'

    const body = `
${header(ctx, 'ஒப்பு நோக்கு பட்டியல்', 'Comparative Statement')}
<p class="ta">${escape(ctx.tender.title_ta ?? '')}</p>
<p>${escape(ctx.tender.title_en ?? '')}</p>
<table>
  <thead><tr><th></th>${cols}</tr></thead>
  <tbody>
    <tr><th class="ta">விலை / Amount</th>${amounts}</tr>
    <tr><th class="ta">தொலைபேசி / Phone</th>${phones}</tr>
  </tbody>
</table>
${l1Id != null ? `<p class="ta"><strong>குறைந்த விலையாளர் (L1):</strong> ${escape(active.find((q) => q.id === l1Id)!.submitter_name)} — ₹ ${fmtAmount(active.find((q) => q.id === l1Id)!.amount)}</p>` : ''}
${l1Id != null ? `<p><strong>Lowest bidder (L1):</strong> ${escape(active.find((q) => q.id === l1Id)!.submitter_name)} — Rs. ${fmtAmount(active.find((q) => q.id === l1Id)!.amount)}</p>` : ''}
<div class="footer">
  <div></div>
  <div><div class="ta">தனி அலுவலர் / Special Officer</div><div class="sig">Signature</div></div>
</div>`
    return SHELL('Comparative', body).replace('{tenderId}', String(ctx.tender.id)).replace('{ver}', String(ctx.document.version))
}

// ── 4. Work order ─────────────────────────────────────────────────────────
const DEFAULT_CONDITIONS = [
    'பணி குறிப்பிட்ட காலக்கெடுவுக்குள் முடிக்க வேண்டும். / Work to be completed within the stipulated period.',
    'பணியின் தரம் ஊராட்சி அலுவலர் மேற்பார்வையில் உறுதி செய்யப்பட வேண்டும். / Quality must be supervised by panchayat officer.',
    'நிபந்தனை மீறினால் ஒப்பந்தம் ரத்து செய்யப்படும். / Breach voids the contract.',
    'விலைப்புள்ளி அளவில் கூடுதல் கட்டணம் கோர முடியாது. / No additional charges beyond quoted amount.',
]

export function renderWorkOrder(ctx: TemplateContext): string {
    const awarded = ctx.quotations.find((q) => q.id === ctx.awarded_quotation_id)
    const completion = ctx.timeline.completion_deadline ?? fmtDate(ctx.tender.work_order_date)
    const overrides = (ctx.document.field_overrides ?? {}) as Record<string, any>
    const conditions: string[] = Array.isArray(overrides.conditions) ? overrides.conditions : DEFAULT_CONDITIONS

    const body = `
${header(ctx, 'வேலை உத்தரவு', 'Work Order')}
<p><strong>Tender:</strong> #${ctx.tender.id} <span class="ta">${escape(ctx.tender.title_ta ?? '')}</span></p>
<p><strong>Work order date:</strong> ${fmtDate(ctx.tender.work_order_date)}</p>
<div class="grid">
  <div><strong class="ta">ஒப்பந்ததாரர் / Contractor:</strong><br/>${awarded ? escape(awarded.submitter_name) : '—'}<br/>${awarded ? escape(awarded.submitter_phone_e164) : ''}</div>
  <div><strong>Awarded amount:</strong><br/>₹ ${awarded ? fmtAmount(awarded.amount) : '—'}<br/>
    <span class="ta small">${awarded ? escape(rupeesInWordsTa(Number(awarded.amount))) : ''}</span><br/>
    <span class="small">${awarded ? escape(rupeesInWordsEn(Number(awarded.amount))) : ''}</span>
  </div>
</div>
<p class="ta">${escape(ctx.tender.narrative_ta ?? '')}</p>
<p>${escape(ctx.tender.narrative_en ?? '')}</p>
${lineItemsTable(ctx)}
<p><strong>Completion deadline / நிறைவு தேதி:</strong> ${completion}</p>
<h3 class="ta">நிபந்தனைகள் / Conditions</h3>
<ol class="conditions">${conditions.map((c) => `<li class="ta">${escape(c)}</li>`).join('')}</ol>
<div class="footer">
  <div>
    <div><strong>Distribution / பரப்பீடு:</strong></div>
    <ol class="small">
      <li>Awardee / ஒப்பந்ததாரர்</li>
      <li>Panchayat Office Records</li>
      <li>Block Development Office</li>
    </ol>
  </div>
  <div><div class="ta">தனி அலுவலர் / Special Officer</div><div class="sig">Signature</div></div>
</div>`
    return SHELL('Work Order', body).replace('{tenderId}', String(ctx.tender.id)).replace('{ver}', String(ctx.document.version))
}

// ── 5. SO Proceedings (payment authorization) ─────────────────────────────
export function renderSoProceedings(ctx: TemplateContext): string {
    const pm = ctx.payment_meta ?? {}
    const amount = Number(pm.payment_amount ?? 0)
    const body = `
${header(ctx, 'தனி அலுவலர் ... நடவடிக்கைகள்', 'Special Officer — Proceedings (Payment Authorization)')}
<table>
  <tr><th class="ta">நடவடிக்கை எண் (NK No.)</th><td>${escape(pm.nk_number ?? '—')}</td></tr>
  <tr><th>Proceedings date</th><td>${escape(pm.so_proceedings_date ?? '—')}</td></tr>
  <tr><th class="ta">பணி / Subject</th><td class="ta">${escape(ctx.tender.title_ta ?? '')} <br/>${escape(ctx.tender.title_en ?? '')}</td></tr>
  <tr><th>Bill / MB / Resolution refs</th><td>${Array.isArray(pm.bill_mb_resolution_refs) ? (pm.bill_mb_resolution_refs as string[]).map(escape).join(', ') : escape(pm.bill_mb_resolution_refs ?? '—')}</td></tr>
  <tr><th>Expense head</th><td>${escape(pm.expense_head ?? '—')}</td></tr>
  <tr><th>Amount (figures)</th><td class="amount">₹ ${fmtAmount(String(amount))}</td></tr>
  <tr><th>Amount (words)</th><td class="ta">${escape(pm.payment_amount_in_words_ta ?? rupeesInWordsTa(amount))}<br/><span class="small">${escape(pm.payment_amount_in_words_en ?? rupeesInWordsEn(amount))}</span></td></tr>
  <tr><th>Payee</th><td>${escape((ctx.quotations.find((q) => q.id === ctx.awarded_quotation_id)?.submitter_name) ?? '—')}</td></tr>
  ${pm.payment_method === 'tnpass' ? `<tr><th>TNPASS ref</th><td>${escape(pm.tnpass_ref ?? '—')} (${escape(pm.tnpass_date ?? '—')})</td></tr>` : ''}
  ${pm.payment_method === 'cheque' ? `<tr><th>Cheque</th><td>${escape(pm.cheque_no ?? '—')} (${escape(pm.cheque_bank ?? '—')}, ${escape(pm.cheque_date ?? '—')})</td></tr>` : ''}
</table>
<p>Resolved that the above expenditure of <strong>₹ ${fmtAmount(String(amount))}</strong> be paid to the contractor and ratified.</p>
<div class="footer">
  <div></div>
  <div><div class="ta">தனி அலுவலர் / Special Officer</div><div class="sig">Signature</div></div>
</div>`
    return SHELL('SO Proceedings', body).replace('{tenderId}', String(ctx.tender.id)).replace('{ver}', String(ctx.document.version))
}

// ── 6. Form 19 (expenditure voucher) ──────────────────────────────────────
export function renderForm19(ctx: TemplateContext): string {
    const pm = ctx.payment_meta ?? {}
    const amount = Number(pm.payment_amount ?? 0)
    const awarded = ctx.quotations.find((q) => q.id === ctx.awarded_quotation_id)
    const body = `
${header(ctx, 'செலவினச் சீட்டு (படிவம் 19)', 'Expenditure Voucher — Form 19')}
<div class="grid">
  <div><strong>Voucher No / சீட்டு எண்:</strong> ${escape(pm.voucher_serial ?? '—')}</div>
  <div><strong>Date / தேதி:</strong> ${escape(pm.voucher_date ?? '—')}</div>
</div>
<p><strong>Expense head / செலவின் தலைப்பு:</strong> ${escape(pm.expense_head ?? '—')}</p>
<p><strong>Payee / பெறுநர்:</strong> ${escape(awarded?.submitter_name ?? pm.payee_name ?? '—')}</p>
<table>
  <thead><tr><th>#</th><th class="ta">விவரம் / Description</th><th>Amount (₹)</th></tr></thead>
  <tbody>
    <tr>
      <td>1</td>
      <td class="ta">${escape(ctx.tender.title_ta ?? ctx.tender.title_en ?? '')}<br/><span class="small">${escape(ctx.tender.title_en ?? '')}</span></td>
      <td class="amount">${fmtAmount(String(amount))}</td>
    </tr>
    <tr><th colspan="2" class="right">Total</th><td class="amount"><strong>${fmtAmount(String(amount))}</strong></td></tr>
  </tbody>
</table>
<p><strong>Amount in words / தொகை எழுத்தில்:</strong></p>
<p class="ta">${escape(pm.payment_amount_in_words_ta ?? rupeesInWordsTa(amount))}</p>
<p>${escape(pm.payment_amount_in_words_en ?? rupeesInWordsEn(amount))}</p>
${pm.payment_method === 'tnpass' ? `<p><strong>Paid via TNPASS:</strong> Ref ${escape(pm.tnpass_ref ?? '—')}, Date ${escape(pm.tnpass_date ?? '—')}</p>` : ''}
${pm.payment_method === 'cheque' ? `<p><strong>Paid via cheque:</strong> ${escape(pm.cheque_no ?? '—')} drawn on ${escape(pm.cheque_bank ?? '—')}, dated ${escape(pm.cheque_date ?? '—')}</p>` : ''}
<p><strong>Passed for Rupees ${fmtAmount(String(amount))}</strong> (<span class="ta">${escape(rupeesInWordsTa(amount))}</span>)</p>
<p class="small muted">I certify that the work described has been carried out and the expenditure is necessary and reasonable.</p>
<div class="footer">
  <div><div>Verified by</div><div class="sig">Account clerk</div></div>
  <div><div class="ta">தனி அலுவலர் / Special Officer</div><div class="sig">Signature</div></div>
</div>`
    return SHELL('Form 19', body).replace('{tenderId}', String(ctx.tender.id)).replace('{ver}', String(ctx.document.version))
}

export function renderTemplate(templateId: string, ctx: TemplateContext): string {
    switch (templateId) {
        case 'rfq': return renderRfq(ctx)
        case 'quotation': return renderQuotation(ctx)
        case 'comparative': return renderComparative(ctx)
        case 'work_order': return renderWorkOrder(ctx)
        case 'so_proceedings': return renderSoProceedings(ctx)
        case 'form19': return renderForm19(ctx)
        default: throw new Error(`Unknown template id: ${templateId}`)
    }
}
