name: ivr_frontend
description: "Ooraatchi: Integrated GIS-Map & E-Tendering Project Management System for Local Bodies"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  dio: ^5.7.0
  go_router: ^14.8.1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  fl_chart: ^0.70.2
  shimmer: ^3.0.0
  intl: ^0.20.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.4
  path_provider: ^2.1.5
  path: ^1.9.0
  google_maps_flutter: ^2.17.0
  google_maps_flutter_web: ^0.6.0
  flutter_dotenv: ^5.2.1
  share_plus: ^10.1.4
  pointer_interceptor: ^0.10.1
  qr_flutter: ^4.1.0

  web: any
  flutter_tts: ^4.2.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/map_markers/
    - assets/redesign/
    - assets/redesign/backgrounds/
    - assets/redesign/illustrations/
    - assets/redesign/avatars/
